### ISSUE TITLE
Error:RuntimeError: cuda runtime error (11)

### ISSUE THREAD

**Issue by TCChenlong** [DAA233/generative-inpainting-pytorch#9]
Hello, I am Chen Longwhen.When I train the model, I get an error.The error like this.
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:383
My experiment is:
Pytorch 1.1.0
torchvision 0.3.0

**Comment by TCChenlong** [comment]
Thanks a lot!

**Comment by DAA233** [comment]
Hi, @TCChenlong, the error information are too short to check. Could you post more logging information about that?

**Comment by TCChenlong** [comment]
Thanks，I have solved this problem by install torch=1.0.0。
Thanks a lot!

**Comment by DAA233** [comment]
OK, good feedback.
